name = "solidshadw"
compatibility_date = "2025-10-27"

[assets]
directory = "./dist/client"

[observability]
enabled = false
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true